### ISSUE TITLE
followup rolls

### ISSUE THREAD

**Issue by CrysKilljoy** [colinbate/rolltable-requester#5]
When my rolltable has another rolltable as entry, it won't get automatically rolled. 
![image](https://github.com/colinbate/rolltable-requester/assets/70920085/fef244fa-8367-423c-a069-2a66c0107b1b)

When I request my player to roll on a table like this, he will on get the roll for on which table to roll next. If I myself roll on the table directly, i will get the result from the subsequent table as well.

**Comment by colinbate** [comment]
Nested tables is definitely not something I had tested with, and I can definitely see that this would require some specific handling. I'll take a look this weekend.

**Comment by colinbate** [comment]
Just FYI, I am still looking at this. I started investigating, but haven't had the time to finish it. It is top of my list though.

**Comment by CrysKilljoy** [comment]
I'll keep quietly and patiently watching. 
Strongly looking forward the result, though.

**Comment by colinbate** [comment]
This should now be working in version 1.4.0. It can even handle nested tables that are in compendium packs.

**Comment by CrysKilljoy** [comment]
Hey, that was a quick fix, thanks for trhe good work, but I still found a case where it doesn't work quite right.

![image](https://github.com/colinbate/rolltable-requester/assets/70920085/baebef67-9468-4560-8a2b-d64f0e6fd480)

On a table like the following, I made it, that there will be a text for every roll and the max amount of possible rolls on a another table (for example on a 2 all four rolled items shall be shown and only d4 as in the text can actually be picked. That works as normal roll on the table really good
![image](https://github.com/colinbate/rolltable-requester/assets/70920085/abcef536-88b8-4f89-a235-106e634c9266)

but as requested table it only will show the text entry

![image](https://github.com/colinbate/rolltable-requester/assets/70920085/8ee3439d-93f8-4935-b945-023d14932bb9)


I get, if that would be a too specific usecase to be fixed, but nonetheless, it'd be cool ;)

**Comment by colinbate** [comment]
I didn't even know that roll tables could do that, but I know why it isn't working as I'm only using the first result. Interesting. Let me see if I can match the behavior a bit better.

**Comment by colinbate** [comment]
This should now work in 1.5.0

**Comment by CrysKilljoy** [comment]
Works like a charm, thanks a lot
