### ISSUE TITLE
[Feature Request] Display results in chat

### ISSUE THREAD

**Issue by Stexinator** [colinbate/rolltable-requester#6]
Currently the result is always whispered to GM and he has to reveal it manually.

Could you add an option to make it default to show it?

Thanks

**Comment by colinbate** [comment]
I will look into this the next chance that I get. I don't currently have any settings defined, and I was hoping to avoid them, but this feels like it might be a good use for them.

**Comment by Stexinator** [comment]
I solved my use case in another way
